import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { api, IGame } from "../consts";

const Home: NextPage = ({}) => {
  // const [games, setGames] = useState<IGame[]>(new Array<IGame>());
  // useEffect(() => {
  //   fetchGames();
  // }, []);

  // async function fetchGames() {
  //   const res = await fetch(api + "/games");
  //   setGames(await res.json());
  // }

  return (
    <div>
      <Head>
        <title>Game shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* {games.map(({ img, name }) => (
          <div key={img}>
            <Image src={img} alt={name} width={188} height={188} />
            <h2>{name}</h2>
          </div>
        ))} */}
      </main>
    </div>
  );
};

export default Home;
